name: Build

on:
  workflow_dispatch:

jobs:
  Build:
    runs-on: ubuntu-latest
    env:
      TZ: "Asia/Shanghai"

    steps:
      - name: 检查仓库
        uses: actions/checkout@v4.1.7
        with:
          ref: master

      - name: 清理日志
        run: |
          git config --local user.email "${{ github.actor }}@users.noreply.github.com"
          git config --local user.name "${{ github.actor }}"
          git checkout --orphan new_branch
          git add -A
          git commit -am "$(TZ='Asia/Shanghai' date +'%Y-%m-%d %H:%M:%S')"
          git branch -D master
          git branch -m master
          git push -f origin master

      - name: 清理日志
        uses: Mattraks/delete-workflow-runs@main
        with:
          retain_days: 0
          keep_minimum_runs: 2